"""add last active field

Revision ID: b18e1a9a03de
Revises: 4116f225a0ba
Create Date: 2023-11-09 19:16:21.245197

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b18e1a9a03de"
down_revision = "4116f225a0ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_active_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.drop_column("last_active_at")

    # ### end Alembic commands ###
