"""strava last updated

Revision ID: 48abdbce9b1b
Revises: d3a221cf91d7
Create Date: 2023-07-23 16:37:21.088485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48abdbce9b1b"
down_revision = "d3a221cf91d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("updated_from_strava_at", sa.DateTime(), nullable=True)
        )

    op.execute("UPDATE athlete SET updated_from_strava_at = created_at;")

    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_from_strava_at", existing_type=sa.DateTime(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.drop_column("updated_from_strava_at")

    # ### end Alembic commands ###
