"""Add strava data

Revision ID: a13c71267756
Revises: 690fbacdda86
Create Date: 2023-05-05 16:44:50.349150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a13c71267756"
down_revision = "690fbacdda86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("first_name", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(sa.Column("last_name", sa.String(length=32), nullable=True))
        batch_op.add_column(
            sa.Column("picture_url", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(sa.Column("strava_id", sa.BigInteger(), nullable=False))
        batch_op.add_column(
            sa.Column("strava_access_token", sa.String(length=128), nullable=False)
        )
        batch_op.add_column(
            sa.Column("strava_access_token_expires_at", sa.DateTime(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("strava_refresh_token", sa.String(length=128), nullable=False)
        )
        batch_op.add_column(sa.Column("strava_raw", sa.JSON(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_athlete_strava_id"), ["strava_id"], unique=True
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_athlete_strava_access_token"), ["strava_access_token"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_athlete_strava_refresh_token"), ["strava_refresh_token"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_athlete_strava_refresh_token"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_athlete_strava_access_token"), type_="unique"
        )
        batch_op.drop_index(batch_op.f("ix_athlete_strava_id"))
        batch_op.drop_column("strava_raw")
        batch_op.drop_column("strava_refresh_token")
        batch_op.drop_column("strava_access_token_expires_at")
        batch_op.drop_column("strava_access_token")
        batch_op.drop_column("strava_id")
        batch_op.drop_column("picture_url")
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    # ### end Alembic commands ###
