"""index jobs by activity

Revision ID: 66559e7d3696
Revises: 97bb8552fd4f
Create Date: 2023-11-07 17:39:58.864142

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "66559e7d3696"
down_revision = "97bb8552fd4f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_fetch_job", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_fetch_job_activity_strava_id"),
            ["activity_strava_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_fetch_job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_fetch_job_activity_strava_id"))

    # ### end Alembic commands ###
