"""add strava token table

Revision ID: 9701de544e8a
Revises: 8adcf1b4cd8e
Create Date: 2023-05-06 09:35:56.187402

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9701de544e8a"
down_revision = "8adcf1b4cd8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strava_token",
        sa.Column("access_token", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("refresh_token", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strava_token")),
    )
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.add_column(sa.Column("strava_token_id", sa.Integer(), nullable=True))
        batch_op.drop_constraint("uq_athlete_strava_access_token", type_="unique")
        batch_op.drop_constraint("uq_athlete_strava_refresh_token", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_athlete_strava_token_id"),
            ["strava_token_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_athlete_strava_token_id_strava_token"),
            "strava_token",
            ["strava_token_id"],
            ["id"],
        )
        batch_op.drop_column("strava_refresh_token")
        batch_op.drop_column("strava_scope")
        batch_op.drop_column("strava_access_token_expires_at")
        batch_op.drop_column("strava_access_token")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "strava_access_token",
                sa.VARCHAR(length=128),
                autoincrement=False,
                nullable=False,
            ),
        )
        batch_op.add_column(
            sa.Column(
                "strava_access_token_expires_at",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=False,
            ),
        )
        batch_op.add_column(
            sa.Column(
                "strava_scope",
                sa.VARCHAR(length=128),
                autoincrement=False,
                nullable=False,
            ),
        )
        batch_op.add_column(
            sa.Column(
                "strava_refresh_token",
                sa.VARCHAR(length=128),
                autoincrement=False,
                nullable=False,
            ),
        )
        batch_op.drop_constraint(
            batch_op.f("fk_athlete_strava_token_id_strava_token"),
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_athlete_strava_token_id"))
        batch_op.create_unique_constraint(
            "uq_athlete_strava_refresh_token",
            ["strava_refresh_token"],
        )
        batch_op.create_unique_constraint(
            "uq_athlete_strava_access_token",
            ["strava_access_token"],
        )
        batch_op.drop_column("strava_token_id")

    op.drop_table("strava_token")
    # ### end Alembic commands ###
