"""job retry count

Revision ID: 744554627216
Revises: 85f901d43b12
Create Date: 2023-11-13 09:21:53.184098

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "744554627216"
down_revision = "85f901d43b12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_fetch_job", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("retry_count", sa.Integer(), nullable=False, default=0),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_fetch_job", schema=None) as batch_op:
        batch_op.drop_column("retry_count")

    # ### end Alembic commands ###
