"""replace done bool by datetime

Revision ID: 97bb8552fd4f
Revises: 88dc05fcfc3a
Create Date: 2023-07-23 20:11:08.063827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97bb8552fd4f"
down_revision = "88dc05fcfc3a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_fetch_job", schema=None) as batch_op:
        batch_op.add_column(sa.Column("done_at", sa.DateTime(), nullable=True))
        batch_op.drop_column("done")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_fetch_job", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("done", sa.BOOLEAN(), autoincrement=False, nullable=False)
        )
        batch_op.drop_column("done_at")

    # ### end Alembic commands ###
