"""add created_activities_jobs_at

Revision ID: 2c86a0e2e460
Revises: 66559e7d3696
Create Date: 2023-11-08 08:40:36.955476

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2c86a0e2e460"
down_revision = "66559e7d3696"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_activities_jobs_at", sa.DateTime(), nullable=True),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.drop_column("created_activities_jobs_at")

    # ### end Alembic commands ###
