"""add activity table

Revision ID: 87dc9c13a451
Revises: 9701de544e8a
Create Date: 2023-05-20 10:13:34.305614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87dc9c13a451"
down_revision = "9701de544e8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("sport_type", sa.String(length=32), nullable=False),
        sa.Column("elapsed_time_in_seconds", sa.Integer(), nullable=False),
        sa.Column("start_datetime", sa.DateTime(), nullable=False),
        sa.Column("city", sa.String(length=128), nullable=False),
        sa.Column("picture_url", sa.String(length=256), nullable=True),
        sa.Column("distance_in_meters", sa.Integer(), nullable=True),
        sa.Column("total_elevation_gain_in_meters", sa.Integer(), nullable=True),
        sa.Column("polyline", sa.Text(), nullable=True),
        sa.Column("strava_id", sa.BigInteger(), nullable=False),
        sa.Column("strava_raw", sa.JSON(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("uuid", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"], ["athlete.id"], name=op.f("fk_activity_athlete_id_athlete")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity")),
    )
    with op.batch_alter_table("activity", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_athlete_id"), ["athlete_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_picture_url"), ["picture_url"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_strava_id"), ["strava_id"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_activity_uuid"), ["uuid"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_uuid"))
        batch_op.drop_index(batch_op.f("ix_activity_strava_id"))
        batch_op.drop_index(batch_op.f("ix_activity_picture_url"))
        batch_op.drop_index(batch_op.f("ix_activity_athlete_id"))

    op.drop_table("activity")
    # ### end Alembic commands ###
