"""add do_after column to jobs

Revision ID: 4116f225a0ba
Revises: 2c86a0e2e460
Create Date: 2023-11-09 15:01:56.993076

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4116f225a0ba"
down_revision = "2c86a0e2e460"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_fetch_job", schema=None) as batch_op:
        batch_op.add_column(sa.Column("do_after", sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_fetch_job", schema=None) as batch_op:
        batch_op.drop_column("do_after")

    # ### end Alembic commands ###
