"""non-nullable settings

Revision ID: 444b8ca55a08
Revises: f277fece4aed
Create Date: 2023-11-22 16:20:05.070811

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "444b8ca55a08"
down_revision = "f277fece4aed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.alter_column("settings_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_index("ix_athlete_settings_id")
        batch_op.drop_index("ix_athlete_strava_token_id")
        batch_op.create_unique_constraint(
            batch_op.f("uq_athlete_settings_id"),
            ["settings_id"],
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_athlete_strava_token_id"),
            ["strava_token_id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_athlete_strava_token_id"),
            type_="unique",
        )
        batch_op.drop_constraint(batch_op.f("uq_athlete_settings_id"), type_="unique")
        batch_op.create_index(
            "ix_athlete_strava_token_id",
            ["strava_token_id"],
            unique=False,
        )
        batch_op.create_index("ix_athlete_settings_id", ["settings_id"], unique=False)
        batch_op.alter_column("settings_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
