"""fields-non-nullable

Revision ID: d3a221cf91d7
Revises: 840607e9ca93
Create Date: 2023-06-11 17:43:24.601010

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d3a221cf91d7"
down_revision = "840607e9ca93"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.alter_column(
            "first_name", existing_type=sa.VARCHAR(length=32), nullable=False
        )
        batch_op.alter_column(
            "last_name", existing_type=sa.VARCHAR(length=32), nullable=False
        )
        batch_op.alter_column(
            "picture_url", existing_type=sa.VARCHAR(length=256), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.alter_column(
            "picture_url", existing_type=sa.VARCHAR(length=256), nullable=True
        )
        batch_op.alter_column(
            "last_name", existing_type=sa.VARCHAR(length=32), nullable=True
        )
        batch_op.alter_column(
            "first_name", existing_type=sa.VARCHAR(length=32), nullable=True
        )

    # ### end Alembic commands ###
