"""store activity jobs

Revision ID: 88dc05fcfc3a
Revises: 48abdbce9b1b
Create Date: 2023-07-23 17:30:14.989302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "88dc05fcfc3a"
down_revision = "48abdbce9b1b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_fetch_job",
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("activity_strava_id", sa.BigInteger(), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete.id"],
            name=op.f("fk_activity_fetch_job_athlete_id_athlete"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_fetch_job")),
    )
    with op.batch_alter_table("activity_fetch_job", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_fetch_job_athlete_id"), ["athlete_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_fetch_job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_fetch_job_athlete_id"))

    op.drop_table("activity_fetch_job")
    # ### end Alembic commands ###
