"""unique email

Revision ID: d250f5653d7f
Revises: 5bc14771d745
Create Date: 2023-11-28 11:47:10.182447

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "d250f5653d7f"
down_revision = "5bc14771d745"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_athlete_email"), ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_athlete_email"), type_="unique")

    # ### end Alembic commands ###
