"""longer activity name

Revision ID: 85f901d43b12
Revises: b18e1a9a03de
Create Date: 2023-11-12 13:01:04.696338

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "85f901d43b12"
down_revision = "b18e1a9a03de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=256),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=256),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
