"""rename current activity to memory in athlete

Revision ID: 9cab90d665e9
Revises: 444b8ca55a08
Create Date: 2023-11-22 18:04:48.845308

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9cab90d665e9"
down_revision = "444b8ca55a08"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("memory_refreshed_at", sa.DateTime(), nullable=True),
        )
        batch_op.drop_column("current_activity_refreshed_at")

    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.execute(
            "UPDATE athlete SET memory_refreshed_at = created_at;",
        )
        batch_op.alter_column(
            "memory_refreshed_at",
            existing_type=sa.DateTime(),
            type_=sa.DateTime(),
            existing_nullable=True,
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "current_activity_refreshed_at",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=False,
            ),
        )
        batch_op.drop_column("memory_refreshed_at")

    # ### end Alembic commands ###
