on:
  push:
    branches:
      - "**"

jobs:
  test:
    if: false
    runs-on: ubuntu-latest
    env:
      APP_CONFIG: "sqlite_testing"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.lock
      - name: Install dev dependencies
        run: pip install -r requirements-dev.lock
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Run migrations
        run: flask db upgrade head
      - name: Run tests
        run: pytest --cov=app --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  deploy-dev:
    runs-on: ubuntu-latest
    # needs: [test]
    if: github.ref == 'refs/heads/main'
    environment: dev
    env:
      APP_CONFIG: "dev"
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      SQLALCHEMY_DATABASE_URI: ${{ secrets.SQLALCHEMY_DATABASE_URI }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
      STRAVA_WEBHOOK_VALIDATION_TOKEN: ${{ secrets.STRAVA_WEBHOOK_VALIDATION_TOKEN }}
      STRAVA_WEBHOOK_SUBSCRIPTION_ID: ${{ secrets.STRAVA_WEBHOOK_SUBSCRIPTION_ID }}
      PHONE_NUMBER_PAUL: ${{ secrets.PHONE_NUMBER_PAUL }}
      PHONE_NUMBER_VINCENT: ${{ secrets.PHONE_NUMBER_VINCENT }}
      SENDBLUE_API_KEY: ${{ secrets.SENDBLUE_API_KEY }}
      SENDBLUE_API_SECRET: ${{ secrets.SENDBLUE_API_SECRET }}
      TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies in virtual env, required for Zappa
        run: | 
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.lock
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Create AWS configuration file
        run: |
          mkdir ~/.aws/
          printf "[profile icloud]\nregion=eu-west-1\noutput=json" > ~/.aws/config
          printf "[icloud]\naws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID_PAUL }}\naws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY_PAUL }}" > ~/.aws/credentials
      - name: Create Zappa configuration file
        run: envsubst < zappa_settings.template.json > zappa_settings.json
      - name: Apply database migrations through bastion instance with SSH
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ec2-18-201-92-197.eu-west-1.compute.amazonaws.com >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add - <<< "${{secrets.BASTION_SSH_PEM}}"
          echo "*:5432:${{ secrets.DATABASE_HOST }}:5432"
          ssh -fN -v -L "*:5432:${{ secrets.DATABASE_HOST }}:5432" ec2-user@ec2-18-201-92-197.eu-west-1.compute.amazonaws.com
          flask db upgrade head
      - name: Update Zappa deployment
        run: |
          source .venv/bin/activate
          zappa update dev