on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_CONFIG: "sqlite_testing"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Setup pipenv
        run: pip install pipenv && pipenv sync --dev
      - name: Run pre-commit
        run: pipenv run pre-commit run --all-files
      - name: Run tests
        run: pipenv run pytest
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    env:
      APP_CONFIG: "development"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Setup pipenv
        run: pip install pipenv && pipenv sync
      - name: Update Zappa deployment
        run: |
          mkdir ~/.aws/
          printf "[profile icloud]\nregion=eu-west-1\noutput=json" > ~/.aws/config
          printf "[icloud]\naws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID_PAUL }}\naws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY_PAUL }}" > ~/.aws/credentials
          pipenv run flask db upgrade head
          pipenv run zappa update