on:
  release:
    types: [published]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    env:
      APP_CONFIG: "prod"
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      SQLALCHEMY_DATABASE_URI: ${{ secrets.SQLALCHEMY_DATABASE_URI }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
      STRAVA_WEBHOOK_VALIDATION_TOKEN: ${{ secrets.STRAVA_WEBHOOK_VALIDATION_TOKEN }}
      STRAVA_WEBHOOK_SUBSCRIPTION_ID: ${{ secrets.STRAVA_WEBHOOK_SUBSCRIPTION_ID }}
      PHONE_NUMBER_PAUL: ${{ secrets.PHONE_NUMBER_PAUL }}
      PHONE_NUMBER_VINCENT: ${{ secrets.PHONE_NUMBER_VINCENT }}
      SENDBLUE_API_KEY: ${{ secrets.SENDBLUE_API_KEY }}
      SENDBLUE_API_SECRET: ${{ secrets.SENDBLUE_API_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r requirements.lock
      - name: Create AWS configuration file
        run: |
          mkdir ~/.aws/
          printf "[profile icloud]\nregion=eu-west-1\noutput=json" > ~/.aws/config
          printf "[icloud]\naws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID_PAUL }}\naws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY_PAUL }}" > ~/.aws/credentials
      - name: Get Github actions IP
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Add Github actions IP to db security group
        id: authorize_runner
        run: |
          aws ec2 authorize-security-group-ingress --profile icloud --group-id sg-09604b54a891618b8 --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32
          echo "exit_code=$?" >> $GITHUB_OUTPUT
      - name: Create Zappa configuration file
        run: envsubst < zappa_settings.template.json > zappa_settings.json
      - name: Apply database migrations
        run: flask db upgrade head
      - name: Update Zappa deployment
        run: zappa update prod
      - name: Revoke Github actions IP to db security group
        if: ${{ steps.authorize_runner.outputs.exit_code }} == 0
        run: aws ec2 revoke-security-group-ingress --profile icloud --group-id sg-09604b54a891618b8 --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32
